# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
    args = ["/Users/SwaggySpencerMcDee/Documents/ee599/ee599-hw3/q6-vect_reader/output.txt"]
)

